### ISSUE TITLE
Transfer to organization

### ISSUE THREAD

**Issue by k8hertweck** [ndcn/omicser#11]
Prior to the first release, the repo ownership should be transferred to the organization.

Other things to check at that time:
- CODE_OF_CONDUCT contact name
- DESCRIPTION Author
- LICENSE
- Shiny App credits in app_ui.R

**Comment by ergonyc** [comment]
👍

**Comment by k8hertweck** [comment]
Repo has been transferred. I still need to replace Andy's personal account info with the new org info

**Comment by ergonyc** [comment]
@k8hertweck what else do we need to do here?

- [ ] official contact email?
- [ ] ?
