### ISSUE TITLE
github actions CI

### ISSUE THREAD

**Issue by ergonyc** [ndcn/omicser#13]
continuous integration with github actions
- [x]  pkgdown live documention website (#7)  
- [x] renv management (#95)
- [ ] cross platform testing ~~(renv enabled)~~

**Comment by k8hertweck** [comment]
If we build a package website (as in #7 ) we won't need to render Rmds here

**Comment by ergonyc** [comment]
pull request #95  begins to solve continuous integrations...  editing above to include testing across platforms.

**Comment by ergonyc** [comment]
removed renv package management.  closing as all remaining issues are resolved for now.  A more comprehensive CI / testing discussion still needs to happen.
