### ISSUE TITLE
omicers::run_docker is not an exported object

### ISSUE THREAD

**Issue by bsenf27** [ndcn/omicser#151]
HI "omicser"

**Describe the bug**
Running the "omicser" docker container based on Dockerfile did not work:
<pre>
> options('shiny.port'=3939,shiny.host='0.0.0.0');omicser::run_docker()
Error: 'run_docker' is not an exported object from 'namespace:omicser'
Execution halted
</pre>

**To Reproduce**
<pre>
docker build -t omicser -f Dockerfile .
docker run --rm -p 3939:3939 -v /mydata/omicser:/root/DB omicser
</pre>

**Expected behavior**
 My workaround:
<pre>
  sed -e 's/run_docker/run_app/' < Dockerfile > Dockerfile.mod
  docker build -t omicser -f Dockerfile.mod .
  docker run -d -v /data/omicser/:/root/DB/ -p 3939:3939 omicser
  # container-id
</pre>

Bernd

**Comment by ricoderks** [comment]
Hi, 

I'll have a look at this.

Cheers, Rico

**Comment by ricoderks** [comment]
@ergonyc I checked this and I noticed that the run_docker functions has dissapeared from run_app.R. Do you know if this happened intentionally? 

Cheers, Rico
