### ISSUE TITLE
additional_info.Rmd not displaying on Ingest tab

### ISSUE THREAD

**Issue by bnovotny** [ndcn/omicser#154]
**Describe the bug**
The default additional_info.Rmd from the omicser package does not display on the Ingest tab. Instead, the Rmd template from RStudio displays, see screenshot. Possible file path issue on Windows?

**To Reproduce**
1. Run omicser (on Windows 10), click on Ingest tab

**Expected behavior**
The contents of omicser/app/www/additional_info.Rmd should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/51127670/149407477-88144940-e30b-48c6-b4e0-bb16ee3982d1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by ricoderks** [comment]
I'll have a look at this. First need to setup a Windows 10 test environment.

**Comment by ricoderks** [comment]
I just setup a Windows 10 test environment and installed omicser, but I don't see your issue. Can you tell which files are in: `omicser\app\www\` ? The omiser folder is the library folder of R, e.g. C:\R\R-4.0.2\library\.

**Comment by bnovotny** [comment]
Hi @ricoderks, in the the `omicser/app/www/` folder I see `additional_info.Rmd`, `favicon.ico`, `info.Rmd`, `logo.svg`, and `welcome.Rmd`. The file `additional_info.Rmd` starts with 
```
## Database Information Document

> This is a PLACEHOLDER!! 

> WIP template

### This Information HAS NOT been curated
``` 

Which I think is the right file, but it's not being displayed in the browser. I will keep poking around and try to find if this is coming from my computer. Thanks!

**Comment by bnovotny** [comment]
Figured it out, I had another additional_info.Rmd in my database folder that was being read. I was thinking that the custom Rmd had to be in the `omicser/app/www/` folder rather than the database folder, so I didn't realize this one was being displayed. All is well now, thank you!
