### ISSUE TITLE
"From the Lab" not displaying lab name

### ISSUE THREAD

**Issue by bnovotny** [ndcn/omicser#156]
**Describe the bug**
On the Ingest tab, after loading data the words "from the lab" appear on the right without the lab's name.

**To Reproduce**
1. Go to ingest tab
2. Select database and click "load data"

**Expected behavior**
Page should read "From the \<name\> lab", displaying the name set under "meta_info: lab:" in the db_config.yml file.

**Screenshots**
![image](https://user-images.githubusercontent.com/51127670/149410428-58ae8251-e06f-4dac-ad98-a2af1e634cd7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 0.0.9.2021-11-03

**Comment by ricoderks** [comment]
PR #163 should resolve this.

**Comment by ergonyc** [comment]
🙌  @ricoderks
