### ISSUE TITLE
-log10(pvals_adj) on volcano plot

### ISSUE THREAD

**Issue by bnovotny** [ndcn/omicser#158]
**Describe the bug**
Volcano plot uses -log10(pvals_adj) for the y-axis of the volcano plot instead of -log10(pvals). To my knowledge it is preferable to use the raw p-value for volcano plots, but either way the y-axis label should reflect what is being plotted.

https://github.com/ndcn/omicser/blob/2d6f90792c358370228d7c95d3705a849ffac234/R/mod_pg_diff_expr.R#L90-L95

**Comment by ricoderks** [comment]
Agree! I'll make sure that the y-axis label will be correct and see if I can add an option to switch between the two.

**Comment by ergonyc** [comment]
thanks @ricoderks !!
