### ISSUE TITLE
Sidebar formatting/omics to add box

### ISSUE THREAD

**Issue by bnovotny** [ndcn/omicser#159]
**Describe the bug**
At some zoom levels the sidebar renders incorrectly and the "add" button does not work as expected.

**To Reproduce**
1. Run omicser with 100% zoom (Chrome on Windows 10)
2. Go to Ingest tab and load data
3. Enter a feature into the "omics to add" box and click "add"

**Expected behavior**
Buttons and boxes shouldn't overlap, "add" button should add a feature to the Target Features box (could be a separate issue).

**Screenshots**
![image](https://user-images.githubusercontent.com/51127670/149415675-d043009b-c830-45cd-b9a1-9583056f3be4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by ergonyc** [comment]
👏👏
