### ISSUE TITLE
Consistent `roxygen2` headers

### ISSUE THREAD

**Issue by k8hertweck** [ndcn/omicser#16]
Currently importing functions (e.g. `require(“package”)`) or using the `package::function` syntax is inconsistent.

**Comment by ergonyc** [comment]
Is mixing them against best practices?
Regardless, the exported functions need to be properly documented:

- [ ]  compute_de_table() 
- [ ]  display_document() | Display a document in Shiny.
- [ ] get_config() | get_config: helper for reading the Config file containing information about the databases
- [ ] get_db_conf() | get_db_conf: helper for reading the database config
- [ ] get_db_meta() | get_db_meta: helper for reading the database meta data
- [ ] pack_anndata_from_csv() | pack_anndata
- [ ] pack_anndata_from_seurat() | pack_anndata_from_seurat
- [ ] run_app() | Run the Shiny Application
- [ ] run_in_browser() | run_in_browser - shortcut to launch in_browser
- [ ] setup_database() | setup_database
- [ ] word_to_markdown() | Convert a Word (docx) to a Markdown (md) file
- [ ] write_config() | write_config: helper for Writing the Config file for setting up the omicser databases
- [ ] write_db_conf() | write_db_conf: helper for writing the ui config options for the database
- [ ] write_db_meta() | write_db_meta: helper for writing the database meta info

**Comment by ergonyc** [comment]
closing, and replacing with a general ongoing "documentaion" issue.
