### ISSUE TITLE
Error message on boxplots before clicking "Plot now"

### ISSUE THREAD

**Issue by bnovotny** [ndcn/omicser#162]
**Describe the bug**
If a point on the volcano plot is clicked before the "Plot Now!" button is activated, an error message appears in place of the boxplot. 

**To Reproduce**
1. Load data on "Ingest" tab
2. Go to "Playground" Tab
3. Go to "Diff Expr" Tab
4. Click on a point on the volcano plot

**Expected behavior**
The boxplots should load, or there should be a message from validate() in the boxplot server such as "Hit 'plot now!' to load boxplots")

**Screenshots**
![image](https://user-images.githubusercontent.com/51127670/149418434-5a454f03-f743-4fa2-94e5-ce074375bb52.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 0.0.9.2021-11-03

**Comment by ergonyc** [comment]
@ricoderks crushing bugs left and right!!👟🪳
