### ISSUE TITLE
Add button not rendering properly

### ISSUE THREAD

**Issue by ricoderks** [ndcn/omicser#167]
**Describe the bug**
The add button in the side selector is not showing the curved arrow up in Windows 10.

**To Reproduce**
Open the app and go to ingest.

**Expected behavior**
The app should show a curved arrow pointing upwards after the word add.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 96.0.1
 - Version 0.0.9.2021.11.3

**Comment by ergonyc** [comment]
@ricoderks is winning!!
