### ISSUE TITLE
Support QC reporting

### ISSUE THREAD

**Issue by k8hertweck** [ndcn/omicser#17]
Add report tab for quality control assessment

**Comment by ergonyc** [comment]
Place holder tab is present.   

- [ ] agenda topic at next dev meeting: how QC, materials & methods, and other levels of of the study/DATABASE meta-information is best shared.

**Comment by ergonyc** [comment]
Going to close for now and flag this as something that should become part of a larger "module" discussion about adding lab/omic type specific tabs and functionality.
