### ISSUE TITLE
Can't save added database

### ISSUE THREAD

**Issue by ricoderks** [ndcn/omicser#197]
**Describe the bug**
When adding a new database the Update&Close button doesn't get enabled.

**To Reproduce**
1. Go to `Add database`.
2. Select the new database folder you want to add.
3. Fill in a database name.
4. Click `Add database!`.

**Expected behavior**
The Update&Close button should become active.

**Desktop (please complete the following information):**
 - OS: KUbuntu 20.04
 - Browser: firefox
 - Version 99.0

**Comment by ricoderks** [comment]
@ergonyc I fixed this. What would be the correct branch to make a pr to?

Cheers ,Rico

**Comment by ergonyc** [comment]
@ricoderks missed this.  Since its a bug I think we should merge into the main, and then also pull it into the main-dev

**Comment by ricoderks** [comment]
PR #198 should fix this.
