### ISSUE TITLE
golem install missing

### ISSUE THREAD

**Issue by cjsifuen** [ndcn/omicser#27]
`golem` installation is not defined either in:  
- install instructions
- automatic installs

**Comment by ergonyc** [comment]
Golem is listed in the `imports` of the "DESCRIPTION" file... So it should automatically pull from CRAN when installing.   How did you attempt to install?  Maybe its an issue with the "packaged" alpha version?

**Comment by cjsifuen** [comment]
I'll double-check. I searched the repo for `golem` and didn't find anything, but this was when I forked the repo a few weeks ago. Since then, several changed have been made. I'll refork and let you know if I have the same issue.
