### ISSUE TITLE
link rendering

### ISSUE THREAD

**Issue by k8hertweck** [ndcn/omicser#36]
We have links to the website currently hard-coded into several pages (specifically the README and quickstart guides). We should be able to link to the relevant file and let pkgdown render the links, which would make our lives easier in the future.

**Comment by k8hertweck** [comment]
It's possible to [autolink to vignettes](https://pkgdown.r-lib.org/articles/linking.html), though it ends up looking kind of ugly on the website and also doesn't allow linking from the README. I'm kind of inclined to leave them as hard links, even though they'll have to be updated when the repo moves.

**Comment by ergonyc** [comment]
mostly cleaned up... closing with caveat that as testing/"coverage" and other hygiene gets rolled in we will revistit
