### ISSUE TITLE
UI reformulate - "Quantities" playground tab 

### ISSUE THREAD

**Issue by ergonyc** [ndcn/omicser#43]
The box-plots for quantities contained in either the sample or omic meta-data tables often produce "distributions" which are not meaningful statistical objects.  We should remove them and focus on the "heatmap" of the data-matrix.  
The marginal statistics should be reformulated to be "marginal"

- [x] redact boxplots/violin plots of obs and var tables
- [x] heatmap of "all" omics (rendered as png / non-interactive
- [x] heatmap of "selected" omics (or aggregated categories)
- [ ] grouping (automatic and via meta-column)

**Comment by ricoderks** [comment]
You want the default to be all features in the heatmap and a checkbox or something like that to select targeted features (target_omics from the yml file)?
