### ISSUE TITLE
python environment setup

### ISSUE THREAD

**Issue by ergonyc** [ndcn/omicser#44]
There are recurrent bugs in the `reticulate::python` environment.   There are myriad reasons, but the solution is to 

- [ ] create omicser helper function to assert the python environment AND the envirnoment management tool (conda and/or mini-conda) are FORCED to load the right versions
- [ ] clarify/expand documentation of environment setup and how/when `reticulate` is leveraged

This replaces issue #28 & #31 which will be closed.

**Comment by ricoderks** [comment]
I also had a few times, while it was initialy working, that everything stopped working (could not load module scanpy) and R could not find the correct version of python. The solution for me was in Rstudio (Project options) to set the python version to use.

Tools -> Project Options -> Python -> Python interpreter

**Comment by ergonyc** [comment]
Solved by forcing  RETICULATED_PYTHON Renvironment variable as in the documentaion.
