### ISSUE TITLE
markdown requirement not specified

### ISSUE THREAD

**Issue by cjsifuen** [ndcn/omicser#46]
**Error**
Error when following the `Installation and Usage for Viewers` directions. There is no mention of `markdown` as a dependency. Running without `markdown` results in the following error

![image](https://user-images.githubusercontent.com/7724691/135867633-77e7da0a-b166-4d11-9d24-827cb7bc3b30.png)

**Solution**
Installing `markdown` with `install.packages('markdown')` allows the app to start up. We can add this to the directions, or handle this install ourselves.

Thoughts?

**Comment by ergonyc** [comment]
Should check where the dependency is spawned...  there's some shiny rendering of Rmd files, and a (currently unused) helper function in `mod_additional_info.R` to convert a .docx file to markdown for rendering.  Probably don't need the dependency if we wrap with rmarkdown or use shiny wrapper?
