### ISSUE TITLE
Revise inst/app/www

### ISSUE THREAD

**Issue by k8hertweck** [ndcn/omicser#52]
inst/app/www includes the pages that are rendered when the configured browser app is viewed. 

The basic web address (referenced for folks to find help) is handled in #51 . We should scope out what other info should be visible on this page, and perhaps also include placeholders (FIXME) for curators who want to customize the information?

**Comment by ergonyc** [comment]
Need to refine/update:

- [ ] 
- [ ] welcome.Rmd
- [ ] additional_info.Rmd - the "fallback" informational page to render if one has not been curated as part of a dataset

There are also some logo/images files here.  Should we also force the database configuration information (currently in `omicser_options.yml`) to be written here?  Might be the best way to encapsulate and simplify installation/configuration
