### ISSUE TITLE
rationalize config / options.yml

### ISSUE THREAD

**Issue by ergonyc** [ndcn/omicser#97]
I think 
"browser_config.yml" (from omicser_options.yml)
and
"db_config.yml"

are probably sensible... they are most correctly "config"urations.   but is it confusing to have two types of configs?

**Comment by k8hertweck** [comment]
I like the names you're proposing. The way I've [written the vignettes](https://ndcn.github.io/omicser/articles/04_configuration.html)  specifies two separate configurations, and it makes sense to me. Let me know if you update the code and I'll update the vignettes.

**Comment by ergonyc** [comment]
I will make the change this weekend. as I work through what's needed with the 

1. UI simplificiation/changes and 
2. interactivity in the ingestor Tab
3. renv encapsulation..  (might not need to deal with python environments at all!  still testing)

Next week for scrubbing the documentation.

**Comment by ergonyc** [comment]
This is 90% complete... TODO:

- [ ] use golem_opts in run_app() and some wrapper functions to handle the configurations...
- [ ] fallback .yml in /inst/app
- [ ] interactive UI for confugration.
- [ ] simplified configs/defaults
